CREATE TABLE IF NOT EXISTS "HORAS_DIURNAS_MENSUALES" (
	"idHorasDiurnasMensuales"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"latitud"	REAL NOT NULL,
	"mes"	INTEGER NOT NULL,
	"porcentajeHoras"	REAL NOT NULL
);